### PR TITLE
Fix #211: Allow other primary keys than id for infer_schema

### LINKED ISSUE #211: `infer_schema!` blows up on tables with primary keys other than `id`
Not only that, but the error message gives absolutely nothing useful.

```
<diesel macros>:22:19: 16:16 error: use of undeclared type name `columns::id` [E0412]
(internal compiler error: unprintable span)
<diesel macros>:15:1: 17:58 note: in this expansion of table_body! (defined in <diesel macros>)
<diesel macros>:5:1: 6:2 note: in this expansion of table! (defined in <diesel macros>)
<diesel macros>:2:1: 2:64 note: in this expansion of table! (defined in <diesel macros>)
src/schema.rs:2:1: 2:40 note: in this expansion of table! (defined in <diesel macros>)
```

We can't *fully* solve this without adding composite primary key support, but we should try to handle singular primary keys other than id, and either skip tables with composite primary keys or at least give a more useful warning/error.

### PR DESCRIPTION
**Pull request by weiznich**
* Implement detection of primary keys
* Print an error if there is a composite primary key
* If there is only one primary key, use this one

### CODE REVIEW

File: diesel_codegen/src/schema_inference/mod.rs [hunk 1]
```diff
@@ -149,11 +165,14 @@ fn establish_connection(
 ) -> Result<InferConnection, Box<MacResult>> {
     match database_url {
         #[cfg(feature = "postgres")]
-        _ if database_url.starts_with("postgres://") || database_url.starts_with("postgresql://") => {
-            establish_real_connection(cx, sp, database_url).map(|c| InferConnection::Pg(c))
+        _ if database_url.starts_with("postgres://") ||
+            database_url.starts_with("postgresql://") => {
+                establish_real_connection(cx, sp, database_url)
+                    .map(|c| InferConnection::Pg(c))
```
Comment (sgrif) [inline diesel_codegen/src/schema_inference/mod.rs]: Why did you change the format of these lines?

File: diesel_codegen/src/schema_inference/pg.rs [hunk 2]
```diff
@@ -16,19 +16,21 @@ table! {
...
         attisdropped -> Bool,
+        atttypmod -> Integer,
     }
 }
-
 table! {
-    pg_type (oid) {
-        oid -> Oid,
-        typname -> VarChar,
+    pg_index(indrelid){
```
Comment (sgrif) [inline diesel_codegen/src/schema_inference/pg.rs]: Please follow the style that was used before.

File: diesel_codegen/src/schema_inference/pg.rs [hunk 3]
```diff
@@ -38,11 +40,11 @@ table! {
 }
 
 pub fn determine_column_type(cx: &mut ExtCtxt, attr: &ColumnInformation) -> P<ast::Ty> {
-    let tpe = if attr.type_name.starts_with("_") {
-        let subtype = str_to_ident(&capitalize(&attr.type_name[1..]));
+    let tpe = if attr.type_name.ends_with("[]") {
```
Comment (sgrif) [inline diesel_codegen/src/schema_inference/pg.rs]: What was the purpose of this change? There are array types that don't end with `[]`

Comment (weiznich) [inline diesel_codegen/src/schema_inference/pg.rs]: I've changed the query to get the column informations. Resulting of this the type names changed a bit. One of this changes results in a rename of the array type names. They don't start with _ anymore, but they seems to end with [] now.
Check this query
```sql
select oid::regtype, typname from pg_type where typname like '\_%';
```

Comment (sgrif) [inline diesel_codegen/src/schema_inference/pg.rs]: Is there a reason this needed to change?

Comment (weiznich) [inline diesel_codegen/src/schema_inference/pg.rs]: Informations relating to primary keys living in pg_index, informations about datatypes in pg_types and column related stuff in pg_attributes.
I couldn't get more than one join working, so I decided to rewrite the data type part of the query to use a cast, instead a join to get name of the data type. Unfortunately this results in this changes.

Comment (sgrif) [inline diesel_codegen/src/schema_inference/pg.rs]: Seems like we could just do a separate query to get the primary key name? (Which is what we ultimately need). This would result in much less code changing to support it.

```rust
fn primary_key_name(conn: &PgConnection, table_oid: u32) -> Vec<String> {
    pg_index
        .inner_join(pg_attribute)
        .select(attname)
        .filter(indisprimary.eq(true))
        .filter(attrelid.eq(table_oid))
        .load(&connection)
}
```

Comment (weiznich) [inline diesel_codegen/src/schema_inference/pg.rs]: I considered first to implement this using 2 queries, but decided against it. My concerns with this solution are, that you will need to build the ColumnInformation struct by hand.

If you don't like the current implementation, I can change this back.
Maybe the best solution would be to get this working with two joins.

Comment (sgrif) [inline diesel_codegen/src/schema_inference/pg.rs]: I don't think this needs to be on the `ColumnInformation` struct. Ultimately we pass the primary key name independently of where that struct is used.

Two joins is high on the list, but it would be incredibly painful to use until some changes land in Rust or I figure out a workaround.

Comment (weiznich) [inline diesel_codegen/src/schema_inference/pg.rs]: Returning the primary keys independently would be a way, but then bigger changes on sqlite side would be required. I will look into this tomorrow.

File: diesel_codegen/src/schema_inference/mod.rs [hunk 4]
```diff
@@ -92,15 +92,24 @@ fn table_macro_call(
...
+                    &format!("table {} has {} primary keys, only one is currently supported",
+                        table_name, primary_keys.len()));
+                Err(DummyResult::any(sp))
+            } else {
+                let tokens = data.iter().map(|a| column_def_tokens(cx, a, &connection))
+                    .collect::<Vec<_>>();
+                let table_name = str_to_ident(table_name);
+                let primary_key = str_to_ident(&primary_keys[0]);
+                let item = quote_item!(cx, table! {
+                    $table_name($primary_key) {
```
Comment (sgrif) [inline diesel_codegen/src/schema_inference/mod.rs]: `$table_name ($primary_key)` (missing space)

File: diesel_codegen/src/schema_inference/sqlite.rs [hunk 5]
```diff
@@ -62,3 +62,12 @@ pub fn load_table_names(
         .filter(sql::<types::Bool>("type='table' AND name NOT LIKE '\\_\\_%'"));
     query.load(connection)
 }
+
+pub fn get_primary_keys(conn: &SqliteConnection, table_name: &str) -> Vec<String>{
+    conn.execute_pragma::<pragma_table_info::SqlType, (i32, String, String, bool, Option<String>, bool)>(
+        &format!("PRAGMA TABLE_INFO('{}')", table_name))
+        .unwrap()
+        .iter()
+        .filter_map(|i| if i.5 { Some(i.1.clone()) } else { None })
```
Comment (sgrif) [inline diesel_codegen/src/schema_inference/sqlite.rs]: Maybe put this into a struct?

File: diesel_codegen/src/schema_inference/pg.rs [hunk 6]
```diff
@@ -74,17 +83,28 @@ pub fn load_table_names(
...
+
+    let pk_query = pg_index.select(indexrelid)
+        .filter(sql(&format!("pg_index.indrelid = '{}'::regclass",table_name)))
+        .filter(indisprimary.eq(true));
+
+    pg_attribute.select(attname)
+        .filter(attrelid.eq_any(pk_query))
+        .order(attnum)
+        .load(conn)
+        .unwrap()
```
Comment (sgrif) [inline diesel_codegen/src/schema_inference/pg.rs]: Can we avoid using `unwrap` here?

File: diesel_codegen/src/schema_inference/pg.rs [hunk 7]
```diff
@@ -74,17 +83,28 @@ pub fn load_table_names(
...
-fn table_oid(conn: &PgConnection, table_name: &str) -> QueryResult<u32> {
-    use self::pg_class::dsl::*;
-    pg_class.select(oid).filter(relname.eq(table_name)).first(conn)
+pub fn get_primary_keys(conn: &PgConnection, table_name: &str) -> Vec<String> {
+    use self::pg_attribute::dsl::*;
+    use self::pg_index::dsl::{pg_index, indisprimary, indexrelid};
+    use diesel::expression::sql_literal::sql;
+
+    let pk_query = pg_index.select(indexrelid)
+        .filter(sql(&format!("pg_index.indrelid = '{}'::regclass",table_name)))
```
Comment (sgrif) [inline diesel_codegen/src/schema_inference/pg.rs]: Why the cast instead of the `table_oid` function that was there before? (I'd prefer to avoid literal SQL as it's unchecked by the compiler)

Comment (weiznich) [inline diesel_codegen/src/schema_inference/pg.rs]: I removed the raw sql, but inlined the table_oid query as subquery.

**Comment by sgrif** [comment]
@weiznich Is this ready to go?

**Comment by weiznich** [comment]
Yes

**Comment by sgrif** [comment]
Thank you for working on this!
